---
repos:
- repo: local
  hooks:
  - id: super-linter
    name: super-linter
    language: system
    entry: >
      docker run
      -e RUN_LOCAL=true
      -e USE_FIND_ALGORITHM=true
      -e VALIDATE_MARKDOWN=false
      -e VALIDATE_GITHUB_ACTIONS=false
      -e VALIDATE_ANSIBLE=false
      -v /home/damiankolaska/Desktop/todo-list:/tmp/lint
      github/super-linter:v4.7.3 --rm
