---
- name: Deploys static HTML website to a VM
  hosts: "{{ apache_server }}"
  tasks:

  - name: Check server availability
    ping:

  - name: Copy website sources
    synchronize:
      src: ../html/
      dest: "/var/www/html/"
      dest_port: "{{ ansible_ssh_port }}"
      archive: yes
    register: website_sources_changes

  - name: Copy database file
    synchronize:
      src: ../todo.json
      dest: "{{ ansible_user }}@{{ ansible_host }}:/var/www/html/todo.json"
      dest_port: "{{ ansible_ssh_port }}"
    register: json_database

  - name: Add write permissions to todo.json file
    file:
      path: /var/www/html/todo.json
      mode: '666'
    become: yes

  - name: Modify SELinux context to allow apache to modify /var/www/html/todo.json on machines running Fedora
    community.general.sefcontext:
      target: /var/www/html/todo.json 
      setype: httpd_sys_rw_content_t
      state: present
    register: httpd_sefcontext
    when: json_database.changed

  - name: Apply new SELinux file context to filesystem on machines running Fedora 
    ansible.builtin.command: restorecon -irv /var/www/html/
    when: httpd_sefcontext.changed and ansible_distribution == 'Fedora'

  - name: Restart apache service
    service:
      name: "{{ apache_service }}"
      state: restarted
    when: "'php' in website_sources_changes.msg or 'css' in website_sources_changes.msg"