apache_servers:
  hosts:
    local_fedora_vm:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: root
      apache_package: httpd
    local_gcp_debian_vm:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: "{{ lookup('env', 'USER') }}"
      apache_package: apache2
