---
name: 'Provision infrastructure'

on:
  workflow_run:
    workflows: ["Static analysis"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:
    branches: [master]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: hmarr/debug-action@v2
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.2

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${TF_VAR_gcp_project_id}-tf-state"
      env:
        TF_VAR_gcp_project_id: '${{ secrets.GCP_PROJECT_ID }}'
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_gcp_project_id: '${{ secrets.GCP_PROJECT_ID }}'
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_gcp_project_id: '${{ secrets.GCP_PROJECT_ID }}'
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}