---
name: Static analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # Allow to skip this workflow by adding [nolint] tag to commit message
    if: "!contains(github.event.commits[0].message, '[nolint]')"

    name: Lint code base with Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_MARKDOWN: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_ANSIBLE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # [WORKAROUND] This job only purpose is to ensure that workflow does not fall into skipped status,
  # when [nolint] tag is specified. Otherwise subsequent workflows would not run.
  dummy_job:
    name: Dummy job to ensure that 'completed' event is generated.
    runs-on: ubuntu-latest

    steps:
      - name: Dummy job
        run: echo "Dummy job completed"
        shell: bash